name: sapatekno_mvc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  get_it: ^8.2.0
  dio: ^5.9.0
  provider: ^6.1.5
  go_router: ^16.1.0
  intl: ^0.20.2
  path: ^1.9.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.5
  chucker_flutter: ^1.8.5
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  mockito: ^5.5.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  generate: true